import 'package:bitcoin/presentation/add_funds_page/add_funds_page.dart';import 'package:bitcoin/presentation/market_page/market_page.dart';import 'package:bitcoin/presentation/card_one_page/card_one_page.dart';import 'package:bitcoin/presentation/wallet_page/wallet_page.dart';import 'package:bitcoin/widgets/app_bar/custom_app_bar.dart';import 'package:bitcoin/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:bitcoin/widgets/app_bar/appbar_trailing_image.dart';import 'package:bitcoin/widgets/custom_elevated_button.dart';import 'package:bitcoin/widgets/custom_bottom_app_bar.dart';import 'package:bitcoin/widgets/custom_floating_button.dart';import 'package:flutter/material.dart';import 'package:bitcoin/core/app_export.dart';
// ignore_for_file: must_be_immutable
class CardScreen extends StatelessWidget {CardScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(height: 732.v, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 32.v), child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgBackgroundLight, height: 461.v, width: 428.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 26.v)), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildFrame(context), SizedBox(height: 24.v), Text("BTCLE Card", style: CustomTextStyles.headlineSmallWhiteA700), SizedBox(height: 19.v), SizedBox(width: 376.h, child: Text("Lorem ipsum dolor sit amet consectetur. Malesuada adipiscing eu et velit natoque mauris ornare faucibus platea. Lorem ipsum dolor sit amet consectetur. Malesuada adipiscing eu et velit natoque mauris ornare faucibus platea. Lorem ipsum dolor sit amet consectetur. Malesuada adipiscing eu et velit natoque mauris ornare faucibus platea. ", maxLines: 7, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargeBluegray50.copyWith(height: 1.50))), SizedBox(height: 40.v), CustomElevatedButton(text: "Apply Now", buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToBlueGrayDecoration, buttonTextStyle: CustomTextStyles.titleLargeMedium)])))])), bottomNavigationBar: _buildFrame1(context), floatingActionButton: CustomFloatingButton(height: 82, width: 52, child: CustomImageView(imagePath: ImageConstant.imgFrame73, height: 41.0.v, width: 26.0.h)), floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked)); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 92.v, leadingWidth: 60.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgFrame77, margin: EdgeInsets.only(left: 24.h, top: 40.v, bottom: 16.v), onTap: () {onTapCircleImage(context);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgFrame41516, margin: EdgeInsets.fromLTRB(24.h, 40.v, 24.h, 16.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 26.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 5.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgGroup, height: 36.v, width: 123.h), Padding(padding: EdgeInsets.only(top: 10.v, bottom: 11.v), child: Text("Personal", style: CustomTextStyles.bodySmallWhiteA70010))]), SizedBox(height: 40.v), CustomImageView(imagePath: ImageConstant.imgFrame42347, height: 8.v, width: 272.h), SizedBox(height: 34.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Cardholder Name", style: CustomTextStyles.bodyLargeWhiteA700), Text("EXP", style: theme.textTheme.bodyLarge)])])); } 
/// Section Widget
Widget _buildFrame1(BuildContext context) { return CustomBottomAppBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.addFundsPage; case BottomBarEnum.Market: return AppRoutes.marketPage; case BottomBarEnum.Card: return AppRoutes.cardOnePage; case BottomBarEnum.Wallet: return AppRoutes.walletPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.addFundsPage: return AddFundsPage(); case AppRoutes.marketPage: return MarketPage(); case AppRoutes.cardOnePage: return CardOnePage(); case AppRoutes.walletPage: return WalletPage(); default: return DefaultWidget();} } 
/// Navigates to the profileScreen when the action is triggered.
onTapCircleImage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.profileScreen); } 
 }
