import 'package:bitcoin/widgets/app_bar/custom_app_bar.dart';import 'package:bitcoin/widgets/app_bar/appbar_leading_image.dart';import 'package:bitcoin/widgets/app_bar/appbar_title.dart';import 'package:bitcoin/widgets/custom_text_form_field.dart';import 'package:bitcoin/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:bitcoin/core/app_export.dart';
// ignore_for_file: must_be_immutable
class VisaMastercardOneScreen extends StatelessWidget {VisaMastercardOneScreen({Key? key}) : super(key: key);

TextEditingController nameController = TextEditingController();

TextEditingController cardNumberController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(height: 822.v, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 32.v), child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgBackgroundLight, height: 461.v, width: 428.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 5.v)), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildFrame(context), SizedBox(height: 16.v), Text("Enter Card Details", style: theme.textTheme.titleLarge), SizedBox(height: 12.v), Text("Cardholder Name", style: theme.textTheme.bodySmall), SizedBox(height: 3.v), CustomTextFormField(controller: nameController, hintText: "Enter cardholder name", contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 13.v)), SizedBox(height: 15.v), Text("Card Number", style: theme.textTheme.bodySmall), SizedBox(height: 3.v), CustomTextFormField(controller: cardNumberController, hintText: "Enter card number", textInputAction: TextInputAction.done, textInputType: TextInputType.number, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 13.v)), SizedBox(height: 15.v), _buildFrame2(context), SizedBox(height: 60.v), CustomElevatedButton(text: "Buy Now", buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToBlueGrayDecoration, buttonTextStyle: CustomTextStyles.titleLargeMedium)])))]))))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 68.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgFrame41761, margin: EdgeInsets.only(left: 24.h, top: 44.v, bottom: 16.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarTitle(text: "VISA / Mastercard", margin: EdgeInsets.only(top: 52.v, bottom: 23.v)), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 26.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 5.v), CustomImageView(imagePath: ImageConstant.imgHeroiconsCredi, height: 32.adaptSize, width: 32.adaptSize, alignment: Alignment.centerLeft), SizedBox(height: 40.v), CustomImageView(imagePath: ImageConstant.imgFrame42347, height: 8.v, width: 272.h), SizedBox(height: 34.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Cardholder Name", style: CustomTextStyles.bodyLargeBluegray50), Text("EXP", style: theme.textTheme.bodyLarge)])])); } 
/// Section Widget
Widget _buildFrame1(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("EXP Date", style: theme.textTheme.bodySmall), SizedBox(height: 3.v), Container(width: 240.h, padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.card.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("Enter expiry date", style: theme.textTheme.bodyLarge)), CustomImageView(imagePath: ImageConstant.imgCalendar1, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v))]))]); } 
/// Section Widget
Widget _buildFrame2(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildFrame1(context), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("VCC", style: theme.textTheme.bodySmall), SizedBox(height: 3.v), Container(padding: EdgeInsets.all(11.h), decoration: AppDecoration.card.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(right: 4.h), child: Text("VCC number", style: theme.textTheme.bodyLarge))]))])]); } 
/// Navigates to the visaMastercardScreen when the action is triggered.
onTapImage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.visaMastercardScreen); } 
 }
