import 'package:bitcoin/widgets/app_bar/custom_app_bar.dart';import 'package:bitcoin/widgets/app_bar/appbar_leading_image.dart';import 'package:bitcoin/widgets/app_bar/appbar_title.dart';import 'package:bitcoin/widgets/custom_text_form_field.dart';import 'package:bitcoin/widgets/custom_icon_button.dart';import 'package:bitcoin/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:bitcoin/core/app_export.dart';
// ignore_for_file: must_be_immutable
class TransferScreen extends StatelessWidget {TransferScreen({Key? key}) : super(key: key);

TextEditingController amountController = TextEditingController();

TextEditingController amountController1 = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(height: 822.v, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 24.v), child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgBackgroundLight, height: 461.v, width: 428.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 5.v)), _buildFrame(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 68.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgFrame41761, margin: EdgeInsets.only(left: 24.h, top: 44.v, bottom: 16.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarTitle(text: "Transfer", margin: EdgeInsets.only(top: 51.v, bottom: 24.v)), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Transfer", style: theme.textTheme.titleLarge), SizedBox(height: 12.v), Text("From BTCLE", style: theme.textTheme.bodySmall), SizedBox(height: 3.v), CustomTextFormField(controller: amountController, hintText: "BTCLE amount", suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 8.v, 8.h, 8.v), child: CustomImageView(imagePath: ImageConstant.imgClose, height: 32.adaptSize, width: 32.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 48.v)), SizedBox(height: 20.v), CustomIconButton(height: 54.adaptSize, width: 54.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillBlueGrayTL27, alignment: Alignment.center, child: CustomImageView(imagePath: ImageConstant.imgTrade)), SizedBox(height: 15.v), Text("To USDT", style: theme.textTheme.bodySmall), SizedBox(height: 3.v), CustomTextFormField(controller: amountController1, hintText: "USDT amount", textInputAction: TextInputAction.done, suffix: Container(padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 8.v), margin: EdgeInsets.fromLTRB(30.h, 4.v, 4.h, 4.v), decoration: BoxDecoration(color: appTheme.blueGray900, borderRadius: BorderRadius.circular(8.h)), child: CustomImageView(imagePath: ImageConstant.imgDollar1, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 48.v))]), SizedBox(height: 60.v), CustomElevatedButton(text: "Confirm Transfer", buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToBlueGrayDecoration, buttonTextStyle: CustomTextStyles.titleLargeMedium, onPressed: () {onTapConfirmTransfer(context);})]))); } 
/// Navigates to the homeNewProfileUpTabContainerScreen when the action is triggered.
onTapImage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeNewProfileUpTabContainerScreen); } 
/// Navigates to the limitScreen when the action is triggered.
onTapConfirmTransfer(BuildContext context) { Navigator.pushNamed(context, AppRoutes.limitScreen); } 
 }
