import 'package:bitcoin/widgets/app_bar/custom_app_bar.dart';import 'package:bitcoin/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:bitcoin/widgets/app_bar/appbar_trailing_image.dart';import 'package:bitcoin/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:bitcoin/core/app_export.dart';class MarketPage extends StatelessWidget {const MarketPage({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 27.v), child: Column(children: [_buildFrame2(context), SizedBox(height: 14.v), _buildFrame5(context), SizedBox(height: 16.v), _buildFrame8(context), SizedBox(height: 16.v), _buildFrame10(context), SizedBox(height: 1.v), SizedBox(height: 461.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgBackgroundLight, height: 461.v, width: 428.h, alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildFrame11(context), SizedBox(height: 16.v), _buildFrame12(context), SizedBox(height: 16.v), _buildFrame15(context), SizedBox(height: 16.v), _buildFrame17(context), SizedBox(height: 16.v), _buildFrame19(context), SizedBox(height: 16.v), _buildFrame20(context), SizedBox(height: 16.v), _buildFrame21(context), SizedBox(height: 16.v), _buildFrame22(context)])))])), SizedBox(height: 2.v), _buildFrame23(context), SizedBox(height: 16.v), _buildFrame25(context), SizedBox(height: 16.v), _buildFrame27(context), SizedBox(height: 16.v), _buildFrame29(context), SizedBox(height: 16.v), _buildFrame31(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 92.v, leadingWidth: 60.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgFrame77, margin: EdgeInsets.only(left: 24.h, top: 40.v, bottom: 16.v), onTap: () {onTapCircleImage(context);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgFrame41516, margin: EdgeInsets.fromLTRB(24.h, 40.v, 24.h, 16.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildFrame2(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("Coin/Volume", style: theme.textTheme.bodySmall), Spacer(flex: 75), Text("Price", style: theme.textTheme.bodySmall), Spacer(flex: 24), Text("Change", style: theme.textTheme.bodySmall)])); } 
/// Section Widget
Widget _buildTwentyNineThousandSixHundredSeventyThree(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "+296.73%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillLightBlue); } 
/// Section Widget
Widget _buildFrame5(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildFrame(context, close: ImageConstant.imgCloseGray800, gSTUSDT: "GST /USDT"), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), _buildTwentyNineThousandSixHundredSeventyThree(context)])); } 
/// Section Widget
Widget _buildThreeThousandSixHundredOne(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "-36.01%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillRed); } 
/// Section Widget
Widget _buildFrame8(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildFrame(context, close: ImageConstant.imgCloseGray600, gSTUSDT: "GST /USDT"), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), _buildThreeThousandSixHundredOne(context)])); } 
/// Section Widget
Widget _buildTwentyNineThousandSixHundredSeventyThree1(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "+296.73%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillLightBlue); } 
/// Section Widget
Widget _buildFrame10(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCloseGray800, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 9.v), child: Text("GST /USDT", style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), _buildTwentyNineThousandSixHundredSeventyThree1(context)])); } 
/// Section Widget
Widget _buildThreeThousandSixHundredOne1(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "-36.01%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillRed); } 
/// Section Widget
Widget _buildFrame11(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildSeventyOne(context, close: ImageConstant.imgGroup1, gSTUSDT: "GST /USDT", ninetySixThousandFiveHundred: "0.096500", price: " 0.09"), _buildThreeThousandSixHundredOne1(context)]); } 
/// Section Widget
Widget _buildTwentyNineThousandSixHundredSeventyThree2(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "+296.73%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillLightBlue); } 
/// Section Widget
Widget _buildFrame12(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildSeventyOne(context, close: ImageConstant.imgCloseGray800, gSTUSDT: "GST /USDT", ninetySixThousandFiveHundred: "0.096500", price: " 0.09"), _buildTwentyNineThousandSixHundredSeventyThree2(context)]); } 
/// Section Widget
Widget _buildThreeThousandSixHundredOne2(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "-36.01%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillRed); } 
/// Section Widget
Widget _buildFrame15(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildFrame(context, close: ImageConstant.imgClose, gSTUSDT: "GST /USDT"), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), _buildThreeThousandSixHundredOne2(context)]); } 
/// Section Widget
Widget _buildTwentyNineThousandSixHundredSeventyThree3(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "+296.73%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillLightBlue); } 
/// Section Widget
Widget _buildFrame17(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCloseGray800, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 9.v), child: Text("GST /USDT", style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), _buildTwentyNineThousandSixHundredSeventyThree3(context)]); } 
/// Section Widget
Widget _buildThreeThousandSixHundredOne3(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "-36.01%", margin: EdgeInsets.only(top: 4.v, bottom: 3.v), buttonStyle: CustomButtonStyles.fillRed); } 
/// Section Widget
Widget _buildFrame19(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCloseGray90001, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 9.v), child: Text("GST /USDT", style: theme.textTheme.titleMedium)), Spacer(), Container(width: 154.h, margin: EdgeInsets.only(top: 3.v, bottom: 5.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09"), _buildThreeThousandSixHundredOne3(context)]))]); } 
/// Section Widget
Widget _buildTwentyNineThousandSixHundredSeventyThree4(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "+296.73%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillLightBlue); } 
/// Section Widget
Widget _buildFrame20(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildSeventyOne(context, close: ImageConstant.imgCloseGray800, gSTUSDT: "GST /USDT", ninetySixThousandFiveHundred: "0.096500", price: " 0.09"), _buildTwentyNineThousandSixHundredSeventyThree4(context)]); } 
/// Section Widget
Widget _buildThreeThousandSixHundredOne4(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "-36.01%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillRed); } 
/// Section Widget
Widget _buildFrame21(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildSeventyOne(context, close: ImageConstant.imgCloseBlueGray900, gSTUSDT: "GST /USDT", ninetySixThousandFiveHundred: "0.096500", price: " 0.09"), _buildThreeThousandSixHundredOne4(context)]); } 
/// Section Widget
Widget _buildTwentyNineThousandSixHundredSeventyThree5(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "+296.73%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillLightBlue); } 
/// Section Widget
Widget _buildFrame22(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildSeventyOne(context, close: ImageConstant.imgCloseGray800, gSTUSDT: "GST /USDT", ninetySixThousandFiveHundred: "0.096500", price: " 0.09"), _buildTwentyNineThousandSixHundredSeventyThree5(context)]); } 
/// Section Widget
Widget _buildThreeThousandSixHundredOne5(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "-36.01%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillRed); } 
/// Section Widget
Widget _buildFrame23(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildSeventyOne(context, close: ImageConstant.imgClose, gSTUSDT: "GST /USDT", ninetySixThousandFiveHundred: "0.096500", price: " 0.09"), _buildThreeThousandSixHundredOne5(context)])); } 
/// Section Widget
Widget _buildTwentyNineThousandSixHundredSeventyThree6(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "+296.73%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillLightBlue); } 
/// Section Widget
Widget _buildFrame25(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCloseGray800, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 9.v), child: Text("GST /USDT", style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), _buildTwentyNineThousandSixHundredSeventyThree6(context)])); } 
/// Section Widget
Widget _buildFrame27(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgClose, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 9.v), child: Text("GST /USDT", style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), Container(margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 4.v), decoration: AppDecoration.fillRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Text("-36.01%", style: CustomTextStyles.bodySmallOnPrimaryContainer))])); } 
/// Section Widget
Widget _buildTwentyNineThousandSixHundredSeventyThree7(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "+296.73%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillLightBlue); } 
/// Section Widget
Widget _buildFrame29(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCloseGray800, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 14.v, bottom: 14.v), child: Text("GST /USDT", style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), _buildTwentyNineThousandSixHundredSeventyThree7(context)])); } 
/// Section Widget
Widget _buildThreeThousandSixHundredOne6(BuildContext context) { return CustomElevatedButton(height: 23.v, width: 70.h, text: "-36.01%", margin: EdgeInsets.only(left: 30.h, top: 8.v, bottom: 8.v), buttonStyle: CustomButtonStyles.fillRed); } 
/// Section Widget
Widget _buildFrame31(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgClose, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 14.v, bottom: 14.v), child: Text("GST /USDT", style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: _buildFrame1(context, ninetySixThousandFiveHundred: "0.096500", price: " 0.09")), _buildThreeThousandSixHundredOne6(context)])); } 
/// Common widget
Widget _buildFrame(BuildContext context, {required String close, required String gSTUSDT, }) { return SizedBox(width: 131.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: close, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(top: 8.v, bottom: 9.v), child: Text(gSTUSDT, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.blueGray50)))])); } 
/// Common widget
Widget _buildFrame1(BuildContext context, {required String ninetySixThousandFiveHundred, required String price, }) { return Column(children: [Text(ninetySixThousandFiveHundred, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.blueGray50)), Align(alignment: Alignment.centerRight, child: Text(price, style: CustomTextStyles.bodySmallBluegray30010.copyWith(color: appTheme.blueGray300)))]); } 
/// Common widget
Widget _buildSeventyOne(BuildContext context, {required String close, required String gSTUSDT, required String ninetySixThousandFiveHundred, required String price, }) { return Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: close, height: 40.adaptSize, width: 40.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 9.v), child: Text(gSTUSDT, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.blueGray50))), Spacer(), Padding(padding: EdgeInsets.only(top: 3.v, bottom: 5.v), child: Column(children: [Text(ninetySixThousandFiveHundred, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.blueGray50)), Align(alignment: Alignment.centerRight, child: Text(price, style: CustomTextStyles.bodySmallBluegray30010.copyWith(color: appTheme.blueGray300)))]))])); } 
/// Navigates to the profileScreen when the action is triggered.
onTapCircleImage(BuildContext context) { Navigator.pushNamed(context, AppRoutes.profileScreen); } 
 }
