import 'package:bitcoin/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:bitcoin/core/app_export.dart';class BankDepositBottomsheet extends StatelessWidget {const BankDepositBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.customBorderTL32), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(width: 128.h, child: Divider()), SizedBox(height: 32.v), Align(alignment: Alignment.centerLeft, child: Row(children: [CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.fillBlueGray, onTap: () {onTapBtnIconButton(context);}, child: CustomImageView(imagePath: ImageConstant.imgBitcoinIconsEditOutline)), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("Bank Account", style: CustomTextStyles.bodyLargeBluegray50))])), SizedBox(height: 26.v), _buildFrame(context, sWIFTCode: "Your Bank", nBEGEGCX: "AHLI UNITED BANK"), SizedBox(height: 9.v), _buildFrame1(context, iBANNumber: "Local Number", eG: "EG6100030439550016431663000190"), SizedBox(height: 9.v), _buildFrame(context, sWIFTCode: "SWIFT Code", nBEGEGCX: "NBEG EG CX439"), SizedBox(height: 9.v), _buildFrame1(context, iBANNumber: "IBAN Number", eG: "EG560003043950016431663000280"), SizedBox(height: 22.v)])); } 
/// Common widget
Widget _buildFrame(BuildContext context, {required String sWIFTCode, required String nBEGEGCX, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(sWIFTCode, style: theme.textTheme.bodyLarge!.copyWith(color: appTheme.gray600)), Text(nBEGEGCX, style: CustomTextStyles.bodyLargeBluegray50.copyWith(color: appTheme.blueGray50))]); } 
/// Common widget
Widget _buildFrame1(BuildContext context, {required String iBANNumber, required String eG, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(iBANNumber, style: theme.textTheme.bodyLarge!.copyWith(color: appTheme.gray600)), Text(eG, style: CustomTextStyles.bodyLargeBluegray50.copyWith(color: appTheme.blueGray50))]); } 
/// Navigates to the bankDepositOneScreen when the action is triggered.
onTapBtnIconButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.bankDepositOneScreen); } 
 }
